### ISSUE TITLE
Write the webservices in some kind of API spec language and generate client from it

### ISSUE THREAD

**Issue by meetmangukiya** [coala/corobo#123]

**Comment by meetmangukiya** [comment]
RAML - Rest API Modeling Language is one of the candidates. I have already written the file for the coala API. There are client generators based on RAML, but the python support is pretty low and also, RAML 1.0 has pretty less libs since it is a bit recent. Complete list:
1. https://github.com/vmware/nsxramlclient - Is a python2 library, and corobo is python3, so not really usable. https://github.com/vmware/nsxramlclient/issues/20
2. https://github.com/timofurrer-archive/ramlient - this looked pretty good to me API-wise, it dynamically generates the API call functions, etc. But this repo is no longer maintained :(  - https://github.com/timofurrer-archive/ramlient/issues/1

**Comment by meetmangukiya** [comment]
Options that we'd like to weigh:
1. Wait for RAML support to magically appear soon, until then use something else( :point_down: )
2. Write an own API wrapper, coala webservices is pretty small FWIW
3. Make manual API calls

**Comment by jayvdb** [comment]
Building a API docs + wrapper using `ramlfications` & `griffin` would be interesting. https://github.com/spotify/ramlfications/pull/149 to get that CI green.

Have you tried RAMSES , mentioned on http://raml.org/developers/build-your-api ?

It would also be really interesting to use Flask with errbot, via Flask-RAML.

**Comment by meetmangukiya** [comment]
webservices spec will be written in RAML

**Comment by meetmangukiya** [comment]
client generator that'll be used is ramlient
