### ISSUE TITLE
Include link to the gitter message that opened the issue

### ISSUE THREAD

**Issue by meetmangukiya** [coala/corobo#147]

**Comment by meetmangukiya** [comment]
https://github.com/errbotio/err-backend-gitter/issues/15 

Cannot be done unless implemented in the gitter backend :worried:

**Comment by jayvdb** [comment]
Do you plan to fix it upstream?
Is it feasible to run our own fork of that plugin if it isnt merged upstream?

**Comment by meetmangukiya** [comment]
Yes, it might be feasible since the development isn't really that much on that repo, we might miss out on small things, but rebasing on regular intervals can work. But let's wait for upstream to respond :D ?

**Comment by meetmangukiya** [comment]
Fixed upstream :+1:
