### ISSUE TITLE
explain: Add promotion requirements

### ISSUE THREAD

**Issue by co-robo** [coala/corobo#170]
Ported from old cobot repo, opened by @hemangsk - https://gitlab.com/coala/cobot/issues/39
labels: enhancement, difficulty/low

**Comment by ihsavru** [comment]
Can someone please explain this issue?

**Comment by meetmangukiya** [comment]
This issue about adding one more explain term in the explain plugin which you might've figured.

Quoting from docs http://api.coala.io/en/latest/Developers/Newcomers_Guide.html?highlight=developers:
> To become part of the coala developers team, there are a few steps you need to complete. The newcomer process is as follows:
You will start as a newcomer, which is kind of a trial. If you complete the following tasks, you will become a developer at coala:
- run coala on a project of yours
- merge a difficulty/newcomer Pull Request
- review at least a difficulty/newcomer Pull Request
- merge a difficulty/low Pull Request
- review at least a difficulty/low or higher Pull Request

Steps:
1. Append the message here
2. Done! Please keep the key as `promotion` :+1:
