### ISSUE TITLE
AttributeError on receiving/sending messages

### ISSUE THREAD

**Issue by yukiisbored** [coala/corobo#186]
`AttributeError` occurs when the bot received a message and (may be) send a message to the room. It ends up killing the thread pre-maturely thus make the bot "leave the room". This also happens with PMs.

```
corobo_1  | Exception in thread Thread-27:
corobo_1  | Traceback (most recent call last):
corobo_1  |   File "/usr/local/lib/python3.6/threading.py", line 916, in _bootstrap_inner
corobo_1  |     self.run()
corobo_1  |   File "/usr/local/lib/python3.6/threading.py", line 864, in run
corobo_1  |     self._target(*self._args, **self._kwargs)
corobo_1  |   File "/opt/errbot/err-backend-gitter/gitter.py", line 304, in background
corobo_1  |     m.extras = {'id': json_message['id']}
corobo_1  | AttributeError: can't set attribute
```

**Comment by yukiisbored** [comment]
I don't know if this is an upstream problem.

**Comment by meetmangukiya** [comment]
Bug link: https://github.com/errbotio/err-backend-gitter/issues/25
Patch fixing the bug link: https://github.com/errbotio/err-backend-gitter/pull/26

Likely we will have this merged in less than couple of days
