### ISSUE TITLE
Whitespace missing in invite developer success message difficulty/newcomer

### ISSUE THREAD

**Issue by co-robo** [coala/corobo#214]
Opened by @jayvdb

**Comment by vaibhavgarg11** [comment]
with what file is this issue related to ?

**Comment by meetmangukiya** [comment]
@vaibhavgarg11 adding a space between `ourcommunity` here https://github.com/coala/corobo/blob/master/plugins/labhub.py#L31

**Comment by meetmangukiya** [comment]
@vaibhavgarg11 please assign yourself before you start working on the issue. Please go through Newcomer Guide, it is really helpful and has these things already mentioned. http://coala.io/newcomer
