### ISSUE TITLE
Command "corobo" not found

### ISSUE THREAD

**Issue by Makman2** [coala/corobo#220]
From https://github.com/coala/coala/issues/4492

> Coala bot replies : Command "corobo" not found
>
> In the Newcomers_Guide, in several places we find the use of command "corobo" to take the help of coala-> bot. But in gitter chat when used "corobo" , it replied : Command "corobo" not found.

**Comment by Makman2** [comment]
Filed originally by @susg.

**Comment by meetmangukiya** [comment]
@susg can you provide the exact string used to issue the command?

**Comment by susg** [comment]
corobo assign #4485

**Comment by meetmangukiya** [comment]
@susg it is `corobo assign <link>` so if it was this issue it'd be `corobo assign https://github.com/coala/corobo/issues/220`

**Comment by Makman2** [comment]
@meetmangukiya the message is still very bad and needs improvement imo. Wanna reopen the issue for the sake of message improvement?

**Comment by meetmangukiya** [comment]
@Makman2 this is upstream issue, and FWIW, I don't think there is anything that can be done about this. Since it takes all the messages starting with `corobo` as a command.. I'll checkout with errbot community
