### ISSUE TITLE
Daily PR stats plugin

### ISSUE THREAD

**Issue by co-robo** [coala/corobo#224]
Opened by @jayvdb at [gitter/coala/corobo](https://gitter.im/coala/corobo?at=5976d35cf5b3458e307cdb70)

**Comment by meetmangukiya** [comment]
@jayvdb what kind of PR stats? New PRs opened/closed?

**Comment by jayvdb** [comment]
Yup. Very basic.
My idea behind this was that this would be a simple command, and a separate scheduler would invoke this (and other) commands periodically.
