### ISSUE TITLE
Newcomer's shouldn't be assigned to an unlabelled issue.

### ISSUE THREAD

**Issue by co-robo** [coala/corobo#231]
Opened by @Vamshi99 at [gitter//Vamshi99](https://gitter.im//Vamshi99?at=59789a01bc4647297428df7d)

**Comment by meetmangukiya** [comment]
@Vamshi99 did you verify this, please provide a link then, because this should already be happening. It is already implemented.

**Comment by Vamshi99** [comment]
@meetmangukiya Yeah! I verified that, for example see this https://github.com/coala/landing-frontend/issues/162

**Comment by meetmangukiya** [comment]
@Vamshi99 that is `coala-bot`, not `co-robo` assigning the issue, did you miss the username :P ?

**Comment by Vamshi99** [comment]
Okay it works, but I think we need to change the message here[1] that newcomer can't be assigned to an unlabelled issue.

[1] https://github.com/coala/corobo/blob/6d14a8333ae89e8a0ab249242834779b497e133b/plugins/labhub.py#L299-L300

**Comment by Vamshi99** [comment]
Feel free to close this

**Comment by meetmangukiya** [comment]
we don't need to change that, we need to add a new message. `A newcomer cannot be assigned to unlabelled issues`, wanna do it :D ?

**Comment by meetmangukiya** [comment]
Opened https://github.com/coala/corobo/issues/232 in response to https://github.com/coala/corobo/issues/231#issuecomment-318072127
