### ISSUE TITLE
File issue does not work for GitHub Pages repositories

### ISSUE THREAD

**Issue by co-robo** [coala/corobo#252]
It looks like the regex for LabHub issue filer doesn't work for GitHub pages repositories.

examples of repo names:
* coala.github.io
* this.is.legit
Opened by @yukiisbored at [gitter//yukiisbored](https://gitter.im//yukiisbored?at=598af6daee5c9a4c5fa48927)

**Comment by jayvdb** [comment]
This requires writing tests, and that tests are not newcomer level in corobo due to its current state.
