### ISSUE TITLE
explain: Move hard coded explanations out of code

### ISSUE THREAD

**Issue by co-robo** [coala/corobo#257]
It would be nice to be able to add and remove explanations to make it fit for another org.
Opened by @yukiisbored at [gitter//yukiisbored](https://gitter.im//yukiisbored?at=598afb9dbc4647297468dc48)

**Comment by jayvdb** [comment]
This can be done by converting the explanations to use errbot templates.

**Comment by jayvdb** [comment]
The solution for this issue should also use coala to validate the template syntax.
