### ISSUE TITLE
README: Add gitter room badge linking to corobo channel

### ISSUE THREAD

**Issue by co-robo** [coala/corobo#278]
Opened by @meetmangukiya at [gitter/coala/corobo](https://gitter.im/coala/corobo?at=599881a219147ac32315abb9)

**Comment by prashant0598** [comment]
Please assign me this issue and if possible, guide me how can I fix this issue (I am new to open source)

**Comment by Raman1121** [comment]
@meetmangukiya Can you please explain a bit more what needs to be done on this issue?
Also, can you direct me to the location wherever the change is required?

**Comment by meetmangukiya** [comment]
@Raman1121 it seems like @Shreya001 has completed the issue, maybe look for other newcomer issue on the repo :)
