### ISSUE TITLE
Don't build and push docker image if the files in answers directory are not changed

### ISSUE THREAD

**Issue by co-robo** [coala/corobo#280]
Opened by @meetmangukiya at [gitter/coala/coala/offtopic](https://gitter.im/coala/coala/offtopic?at=59a415370cef4fed2eb9b564)

**Comment by meetmangukiya** [comment]
Done via e61571d86d9d9b03ca589d2867ad9c9687bb80e9 and 6a2180918f1ce13e1b50ba952e9f6c80c4373da9 and 98ebcbfc891a842f871ef9d3f45ac39a505899ed
