### ISSUE TITLE
invite "me" could invite username of requester

### ISSUE THREAD

**Issue by jayvdb** [coala/corobo#292]
This was a PR for cobot https://gitlab.com/coala/cobot/merge_requests/34

**Comment by jayvdb** [comment]
c.f. https://github.com/coala/corobo/issues/255

**Comment by supergr35** [comment]
Can this be explained more clearly? The related PR for cobot doesn't seem to be directly related, unless I'm missing something.

**Comment by meetmangukiya** [comment]
The invite command is restricted to only maintainers. This issue is about enhancing invite command such that if `corobo invite me` is called, the user issuing the command will be invited to the org.

Anything else that might be missing @supergr35

**Comment by supergr35** [comment]
Is that necessary considering we have the `Hello World` ? @meetmangukiya
