### ISSUE TITLE
Mention that users need to be a developer (and point to the requirements) if they try to assign a medium issue

### ISSUE THREAD

**Issue by co-robo** [coala/corobo#296]
Opened by @adtac at [gitter/coala/coala](https://gitter.im/coala/coala?at=59c7771dcfeed2eb654459a4)

**Comment by Makman2** [comment]
I think this is done.

**Comment by jayvdb** [comment]
Unassigned due to inactivity

**Comment by jayvdb** [comment]
Merging this into https://github.com/coala/corobo/issues/328
