### ISSUE TITLE
Fix labelling anamoly

### ISSUE THREAD

**Issue by co-robo** [coala/corobo#304]
There are some PRs in review queue which are having both labels - process/wip as well as process/pending review. IMO corobo should use only latest label and remove the older one.
Opened by @prnvdixit at [gitter/coala/coala](https://gitter.im/coala/coala?at=59e668fe614889d475c8f18f)

**Comment by Makman2** [comment]
Yeah see this issue... :P
However, this is an issue with gitmate, moving the issue.

**Comment by Makman2** [comment]
Moved to https://gitlab.com/gitmate/open-source/gitmate-2/issues/195

**Comment by prnvdixit** [comment]
@Makman2 Yeah - I didn't found gitmate repo here (forgot about gitlab 😄)... Seems Right 😉... 👍
