### ISSUE TITLE
Prevent people from being assigned to other peoples pull requests

### ISSUE THREAD

**Issue by co-robo** [coala/corobo#330]
e.g. https://github.com/coala/documentation/pull/489 being assigned by @vipuldcoder, should be an error
Opened by @jayvdb at [Gitter](https://gitter.im/coala/coala?at=5a04be2319147ac32319545a)

**Comment by meetmangukiya** [comment]
@jayvdb it was @gitmate-bot who assigned that pull, @gitmate-bot syncs the assignees on issue with pulls

**Comment by meetmangukiya** [comment]
Not related to corobo

**Comment by Makman2** [comment]
Migrated to https://gitlab.com/gitmate/open-source/gitmate-2/issues/221
