### ISSUE TITLE
Add .editorconfig file

### ISSUE THREAD

**Issue by co-robo** [coala/corobo#331]
Our style follows the example given on http://editorconfig.org/ for Python and YAML
label: difficulty/low initiatives/gci
Opened by @mohitkyadav at [Gitter](https://gitter.im//mohitkyadav?at=5a07240b026aeaa02fffbf13)

**Comment by Makman2** [comment]
See editorconfig file in https://github.com/coala/coala

**Comment by prankshaw** [comment]
Please assign me to this issue

**Comment by nvzard** [comment]
@prankshaw ask a maintainer of Gitter to assign this issue to you.

**Comment by jayvdb** [comment]
@SubbulakshmiRS is building a template for this.

**Comment by jayvdb** [comment]
Needs to import the template from https://gitlab.com/coala/mobans/issues/2

**Comment by jayvdb** [comment]
This issue reserved for Google Code-in task [6310284659523584](https://codein.withgoogle.com/dashboard/tasks/6310284659523584).
