### ISSUE TITLE
corobo help not working

### ISSUE THREAD

**Issue by yashovardhanagrawal** [coala/corobo#334]
When typing 'corobo help' in the gitter channel there is no response from corobo

I think this is an issue to be fixed

**Comment by prnvdixit** [comment]
It is not replying in private chat either? Please check at https://gitter.im/co-robo 😉

**Comment by yashovardhanagrawal** [comment]
@prnvdixit no its not replying in private chat either

**Comment by yashovardhanagrawal** [comment]
actually, in the private chat, none of the corobo commands is working, I think they have not incorporated it there

**Comment by prnvdixit** [comment]
I am confused, it works for me though....
cc @meetmangukiya ^^

**Comment by yashovardhanagrawal** [comment]
It was not working at that time.. I tried it just now again.. same thing 
it started working.
I think then there's no need for this issue

**Comment by yashovardhanagrawal** [comment]
but yeah it is lagging a lot on personal chat... does not respond many a times

**Comment by Makman2** [comment]
Okay then @yashovardhanagrawal open a new issue for that problem, as `corobo help` itself seems to work :)
