### ISSUE TITLE
Mention the coala StackOverflow tag in lmgtfy 

### ISSUE THREAD

**Issue by jayvdb** [coala/corobo#345]
https://gitlab.com/coala/cobot/issues/23

**Comment by 0x48piraj** [comment]
@co-robo Will you please elaborate a little bit more ? I would like to take this task up!

**Comment by prnvdixit** [comment]
@0x48piraj The issue expects you to add https://stackoverflow.com/questions/tagged/coala **appropriately** in the lmgtfy.
Also, you have already taken up a newcomer issue - So, I will also recommend moving to higher difficulty issue and leave the newcomer issues for some actual newcomer 😛 👍.

**Comment by 0x48piraj** [comment]
That's why I didn't assigned this issue to me :wink:

**Comment by prnvdixit** [comment]
@0x48piraj Ahh... that's good.
BTW you should assign yourself the issue only after understanding it properly 😉
Anyway, Welcome to the community :tada:

**Comment by AnirbanBanik1998** [comment]
I would like to work on this issue

**Comment by Makman2** [comment]
Please accept the org invite, then you can be assigned :+1:

**Comment by Dhiraj240** [comment]
@jayvdb Please assign this issue to me as i am new comer and need to upgrade myself in this community.

**Comment by jayvdb** [comment]
@Dhiraj240 , assigned ; sorry for the delay

**Comment by Dhiraj240** [comment]
@jayvdb Sir,do not say sorry.Rightnow, i am unable to recognize what actually i should do ? can i get some illustration?

**Comment by jayvdb** [comment]
@Dhiraj240 did you read everything in this issue?

Have you tried running corobo on your computer?

**Comment by jayvdb** [comment]
Well then you will need to run corobo before you could modify it, otherwise you can not test that you changes work.

**Comment by Dhiraj240** [comment]
@jayvdb Fine, i was silly to ask a question without trying sorry,i will update you in 2 days.

**Comment by Dhiraj240** [comment]
@jayvdb Sorry, i was not up to my words.I was bit caught up with my college fest.I will give PR in coming weeks.Again Sorry for delay.
