### ISSUE TITLE
corobo isnt labelling

### ISSUE THREAD

**Issue by jayvdb** [coala/corobo#351]
e.g. https://gitlab.com/coala/package_manager/issues/162

I've been seeing this a lot lately.  Maybe the corobo function has been removed due to gitmate?  IMO that is not a good approach.

Or maybe something went wrong in the gitlab side of things.
I was retesting https://gitlab.com/coala/cobot/issues/70

**Comment by meetmangukiya** [comment]
Yeah, corobo never had a function to label issues. Since this was already been done by gitmate.

**Comment by Makman2** [comment]
Looks like this issue is invalid ;)
