### ISSUE TITLE
Limit test commands to only operate in test rooms

### ISSUE THREAD

**Issue by jayvdb** [coala/corobo#359]
In the same vein as https://github.com/coala/corobo/issues/358 , commands like `corobo render test` should not be possible on the main rooms, even not in offtopic rooms.

**Comment by jayvdb** [comment]
This can be achieved by modifying the configuration:

http://errbot.io/en/latest/user_guide/administration.html#access-controls

**Comment by mohitkyadav** [comment]
@jayvd adding `render test` to this (line)[https://github.com/coala/corobo/blob/master/config.py#L33] will help?

**Comment by jayvdb** [comment]
Yes, that could work, but it would also be worth testing turning off specific commands in specific rooms, per `ACCESS_CONTROLS` in http://errbot.io/en/latest/_downloads/config-template.py as mentioned previously.
If possible, we do not want people invoking these commands in the main rooms either, even with the results diverted, as lots of "one line" invocations is lots of noise when there are lots of students playing.  They should play in the test rooms, or in direct chat with the bot.

**Comment by mohitkyadav** [comment]
@jayvdb 
I've made changes, 
(commit)[https://github.com/mohitkyadav/corobo/commit/ad783e97496c47f804ab0387a51564918461aaf6]
(travis build)[https://travis-ci.org/mohitkyadav/corobo/builds/307101727] is successful.
Will this help limit the `render test` command only in **cobot-test** room.

**Comment by Makman2** [comment]
Unassigned due to inactivity.

**Comment by RaiVaibhav** [comment]
why open?

**Comment by Makman2** [comment]
No reason, so closing again.
