### ISSUE TITLE
Do not recognize explain while performing another command

### ISSUE THREAD

**Issue by supergr35** [coala/corobo#364]
For example, I could type in
```
corobo file issue coala Foo: explain in docs bar
```
the output would say corobo can't explain that, but it would file the issue

**Comment by jayvdb** [comment]
I believe this is a regex problem, and it applies to every command, and needs a generic fix.

**Comment by jayvdb** [comment]
c.f. https://github.com/coala/corobo/pull/341

**Comment by yashovardhanagrawal** [comment]
but the test for the regex problem are creating errors, .coafile should be updated for that I think

**Comment by supergr35** [comment]
Should we open a general issue to add `^` and `$` to the end of each regex?

**Comment by yashovardhanagrawal** [comment]
@supergr35 actually you're right, I think we should open a general issue for that
and the tests for them also can be done like in my PR #341
