### ISSUE TITLE
Default COBOT_PREFIX should not be the same as the production value

### ISSUE THREAD

**Issue by jayvdb** [coala/corobo#365]
Currently if someone starts the bot, and connects it to a server with a corobo production instance, two bots will respond to any `corobo ...` command, which will get very ugly when there are 20 or 30 kids trying it, allowing kids to play tricks on each other.

**Comment by jayvdb** [comment]
Likewise multiple bots will be responding to `cobot ..` currently, which is best solved by removing that default configuration entirely: https://github.com/coala/corobo/issues/366

**Comment by Makman2** [comment]
Tbh I don't consider this as critical. We can avoid the accidental clashing by forcing the user to pass a custom name for the bot. However, I haven't seen that yet so this sounds to me like an uncommon case. If people want to annoy people by spawning multiple instances that react on the same name, they could still. That's a misuse we can't stop expect individually banning people.
