### ISSUE TITLE
Update README.md to say BOT_ADMINS is space separated list

### ISSUE THREAD

**Issue by jayvdb** [coala/corobo#367]
`BOT_ADMINS` is a space separated list, like `ROOMS` and `IGNORE_USERNAMES`.
The readme should explain this.

**Comment by yashasingh** [comment]
I would like to work on this issue. But corobo won't assign me. Please help.

**Comment by CLiu13** [comment]
@jayvdb Could you assign me to this issue? Working on it for GCI. Thanks!
