### ISSUE TITLE
Deprecate COBOT_PREFIX

### ISSUE THREAD

**Issue by jayvdb** [coala/corobo#370]
The errbot default is `BOT_PREFIX` ; no benefit to having a different env var for corobo.

**Comment by yashasingh** [comment]
@jayvdb I want to take up this issue.

**Comment by Vamshi99** [comment]
@yashasingh You can use `corobo assign <issue_link>` in our gitter channel to get assigned to this issue.

**Comment by yashasingh** [comment]
@Vamshi99 I cannot assign myself this issue, because it does have a newcomer tag. Please help.

**Comment by Makman2** [comment]
`COBOT_PREFIX` should be deprecated, so corobo detects when it's used and gives a warning that it will soon stop working.

**Comment by yashasingh** [comment]
@Makman2 I wanted some guidance over this issue.
To my knowledge, I find changes are to be made only in config.py by replacing COBOT_PREFIX with BOT_PREFIX. But referring file changes in https://github.com/coala/corobo/pull/400/files , Do I have to make changes in any plugin or create one??
Where in the code for deprecating 'COBOT_PREFIX' be written, in which file ? So that corobo detects when it's used and gives a warning that it will soon stop working.

**Comment by Makman2** [comment]
> To my knowledge, I find changes are to be made only in config.py by replacing COBOT_PREFIX with BOT_PREFIX.

Yes.

> Where in the code for deprecating COBOT_PREFIX be written, in which file ? So that corobo detects when it's used and gives a warning that it will soon stop working.

Probably nearby the entrypoint, where you do an env-var check.

**Comment by EverWinter23** [comment]
I would like to take over.

**Comment by Makman2** [comment]
Reassigning due to inactivity.

**Comment by Makman2** [comment]
@EverWinter23 I think you already have a few issues assigned (among them a newcomer issue), so please take harder ones than `difficulty/newcomer` ;)

**Comment by eeshan9815** [comment]
@jayvdb @Makman2 I would like to start contributing by fixing this issue if no one is working on it

**Comment by aashraybhandar1** [comment]
@Makman2  can I be assigned this issue?

**Comment by Makman2** [comment]
@eeshan9815 please read our newcomer guide :) I've assigned @aashraybhandar1 for now, I hope you don't mind. I'm on vacation currently, so don't have really time to overlook everything here.

**Comment by eeshan9815** [comment]
@Makman2 Should I look for some other `difficulty/newcomer` issue?
