### ISSUE TITLE
Rename COBOT_ROOT to BOT_ROOT

### ISSUE THREAD

**Issue by jayvdb** [coala/corobo#371]
The env vars should be consistent with the naming system used by err, and the name "cobot" needs to die.

Need backwards compatibility for `COBOT_ROOT`, with a warning, as it will be removed after people have had a chance to change their scripts.

**Comment by EmilyOng** [comment]
Hello, I would like to work on this but could you point me to the direction what this statement means and how i should go about doing it?

> Need backwards compatibility for COBOT_ROOT, with a warning, as it will be removed after people have had a chance to change their scripts.

Thanks 😄

**Comment by yukiisbored** [comment]
Unassigned per request.

**Comment by EverWinter23** [comment]
Would like to work on it.
