### ISSUE TITLE
review not aligned in the explain list

### ISSUE THREAD

**Issue by co-robo** [coala/corobo#379]
When corobo is asked to explain something it doesn't know about, it displays a list of items it knows about, `review` - the first item in the list is not aligned. difficulty/newcomer
Opened by @RJ722 at [Gitter](https://gitter.im/coala/cobot-test?at=5a1a3d0d6b5080350f2f127d)

**Comment by RJ722** [comment]
Example Output:
```
Sorry, I only know about these things:
review
* closes
* fixes
* commit message
* rebase
* cep
* gitlab
* google
* promotion
```
The correct message should be:
```
Sorry, I only know about these things:
* review
* closes
* fixes
* commit message
* rebase
* cep
* gitlab
* google
* promotion
```

An example message is here: https://gitter.im/coala/cobot-test?at=5a1a3d0dffa3e37919be091c

**Comment by sks444** [comment]
I would like to work on this issue.
