### ISSUE TITLE
File issue should not be permitted in private chat with bot

### ISSUE THREAD

**Issue by co-robo** [coala/corobo#391]
The benefit of filing issues via bot is so that other people can read them before they can be claimed,
allowing others to help detect duplicates, and ensure the issue is correct/desirable.
Also, the archive link for private messages will not work.
Opened by @jayvdb at [Gitter](https://gitter.im//jayvdb?at=5a1ae19ae606d60e340e987e)

**Comment by jayvdb** [comment]
This issue was created in a private message, with the useless archive URL included ;-)

**Comment by nalinbhardwaj** [comment]
I'll take this up. Corobo doesn't want to assign this, but it doesn't seem too hard to me.

**Comment by jayvdb** [comment]
Assigning to current claimer.

**Comment by meetmangukiya** [comment]
Difficulty set is incorrect. Please use `ACCESS_CONTROLS`, see configuration template from errbot.io
