### ISSUE TITLE
Update the default channel list

### ISSUE THREAD

**Issue by co-robo** [coala/corobo#412]
The default list is stored in `config.py`

low, newcomer, gci
Opened by @jayvdb at [Gitter](https://gitter.im/coala/corobo?at=5a1dd1ebe5ed52e26c9d7e76)

**Comment by meetmangukiya** [comment]
You mean gitter room for documentation?

**Comment by Vamshi99** [comment]
Yeah! add gitter documentation channel https://gitter.im/coala/documentation in the channel list.

**Comment by Vamshi99** [comment]
Whoever takes this issue, also add channels mentioned in https://github.com/coala/coala/wiki/Communication-Channels which aren't in default channel list.

**Comment by jayvdb** [comment]
This fix should also remove the `coala/` prefix on all room names, as that is a gitter specific aspect.  When the backend is Zulip instead of gitter, `coala/coala` becomes just `coala` , likewise rooms `coala-bears`, `corobo`, `gci`,  `documentation`, etc.

**Comment by sanket-mali** [comment]
Assign me on this issue

**Comment by sanket-mali** [comment]
please review my pull request.

**Comment by kumar1202** [comment]
@jayvdb Can you assign this to me, if no one is working on it.

**Comment by jayvdb** [comment]
This is a GCI issue.

**Comment by CLiu13** [comment]
May I be assigned to this issue? Thanks!
