### ISSUE TITLE
Bug: labhub returns api url instead of html url

### ISSUE THREAD

**Issue by co-robo** [coala/corobo#426]
Change `.url` to `.web_url`. For more information about the API, see [IGitt repo](https://gitlab.com/gitmate-2/open-source/IGitt)
labels: difficulty/newcomer initiatives/gci
Opened by @meetmangukiya at [Gitter](https://gitter.im/coala/corobo?at=5a203eb9ba39a53f1a03e2d9)

**Comment by jayvdb** [comment]
This isnt just "create issue" ; it applies to all `.url` in `labhub.py`

**Comment by jayvdb** [comment]
Needs test coverage to prevent oddities occuring again
