### ISSUE TITLE
SSL problem with corobo builds

### ISSUE THREAD

**Issue by jayvdb** [coala/corobo#433]
Travis CI and Semaphore CI are both showing errors like

```
Starting new HTTP connection (1): docs.coala.io
From cffi callback <function _verify_callback at 0x7f097d2b89d8>:
Traceback (most recent call last):
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/OpenSSL/SSL.py", line 313, in wrapper
    _lib.X509_up_ref(x509)
AttributeError: module 'lib' has no attribute 'X509_up_ref'
```

Very likely a problem in the versions of the dependencies used by corobo, as Python 3.6.3 builds of `coala/coala` do [not](https://travis-ci.org/jayvdb/coala/jobs/310013750) have a problem.

Very likely to be the recent release of [pyopenssl 17.5.0](https://github.com/pyca/pyopenssl/releases/tag/17.5.0)

**Comment by Mixih** [comment]
The problem is the pin in igitt, see https://gitlab.com/gitmate/open-source/IGitt/blob/master/requirements.txt#L3

**Comment by Mixih** [comment]
I'm reopening this issue so we can track progress

**Comment by Mixih** [comment]
issue created https://gitlab.com/gitmate/open-source/IGitt/issues/91

**Comment by Mixih** [comment]
PR created https://gitlab.com/gitmate/open-source/IGitt/merge_requests/166
