### ISSUE TITLE
.coafile: fix a typo

### ISSUE THREAD

**Issue by bhavishyagopesh** [coala/corobo#451]
Change `[commits]` to `[commit]` as mentioned here https://github.com/coala/corobo/issues/422

**Comment by Makman2** [comment]
@bhavishyagopesh please get assigned to an issue before you start working on it. Reviews won't happen until then.

**Comment by bhavishyagopesh** [comment]
@Makman2  So there weren't any labels, that's why I couldn't  assign myself. Is it okay now?

**Comment by Makman2** [comment]
If labels are missing, always ask to add some ;)

**Comment by bhavishyagopesh** [comment]
Sure thing :)
