### ISSUE TITLE
Change username to target

### ISSUE THREAD

**Issue by Vamshi99** [coala/corobo#479]
Change username to target in `https://github.com/coala/corobo/blob/master/plugins/templates/labhub/errors/not-maintainer.jinja2.md`
label: difficulty/newcomer

**Comment by HarendraSingh22** [comment]
What exactly has to be done? I want to take this issue

**Comment by Vamshi99** [comment]
@HarendraSingh22 Change word `username` to `target`.

**Comment by wyj1026** [comment]
Can I take up this issue?   :)

**Comment by HarendraSingh22** [comment]
@Vamshi99 Assign me to this issue

**Comment by HarendraSingh22** [comment]
@sils Thanks sir ! Very happy to get my first issue assigned by you ! :)

**Comment by HarendraSingh22** [comment]
PR #481 has been made for this issue

**Comment by EverWinter23** [comment]
I would like to resolve this issue.

**Comment by Makman2** [comment]
Reassigning due to inactivity.
