### ISSUE TITLE
Travis builds are broken

### ISSUE THREAD

**Issue by jayvdb** [coala/corobo#495]
A recent change has resulted in constant Travis build problems.

**Comment by jayvdb** [comment]
e.g. https://travis-ci.org/jayvdb/corobo/builds/319023322 is a master build.

The error is with `TestLabHub.test_create_issue_cmd`

```
        testbot_private.assertCommand('!new issue repository this is the title\nbo\ndy',

>                             'You\'re not allowed')

E       AssertionError: 'You're not allowed' not in 'Can't create an issue for a repository that does not exist. Please ensure that the repository is available and owned by the org.'
```

**Comment by jayvdb** [comment]
@Vamshi99 , any idea why the problem only occurred on Travis, and not Semaphore CI?

**Comment by Vamshi99** [comment]
@jayvdb No idea 😞 ,I think something is wrong with semaphore CI.

**Comment by jayvdb** [comment]
Hmm.... I think this didnt fix it.

https://travis-ci.org/jayvdb/corobo/builds/373781532 is rebased, but has the same error.

**Comment by Vamshi99** [comment]
I fixed repository missing thing, that is ACL's issue. As per the test, ACL's aren't working.

**Comment by jayvdb** [comment]
ah, i see
