### ISSUE TITLE
Block gci issue assignment to all users.

### ISSUE THREAD

**Issue by EverWinter23** [coala/corobo#501]
Workaround for https://github.com/coala/corobo/issues/306 as it still hasn't been solved and is difficult to implement. This will serve as a short-term solution to the problem.
The solution being:
1. gci issues will not be assigned to any contributors using corobo.
2. gci members can still claim the issues by commenting on the issue thread.

**Comment by EverWinter23** [comment]
Currently working on it.

**Comment by jayvdb** [comment]
Note that this issue was only relevant while GCI was being run.  But we still need this capability for the next GCI.
