### ISSUE TITLE
Unnecessary self handling of the TestBot

### ISSUE THREAD

**Issue by meetmangukiya** [coala/corobo#529]
https://github.com/coala/corobo/blob/master/tests/coatils_test.py
https://github.com/coala/corobo/blob/master/tests/wolfram_alpha_test.py
https://github.com/coala/corobo/blob/master/tests/answer_test.py

**Comment by nvzard** [comment]
```

While pytest supports receiving fixtures via test function arguments for non-unittest test methods, unittest.TestCase methods cannot directly receive fixture function arguments as implementing that is likely to inflict on the ability to run general unittest.TestCase test suites. Maybe optional support would be possible, though. If unittest finally grows a plugin system that should help as well. In the meanwhile, the above usefixtures and autouse examples should help to mix in pytest fixtures into unittest suites. And of course you can also start to selectively leave away the unittest.TestCase subclassing, use plain asserts and get the unlimited pytest feature set.
```
https://docs.pytest.org/en/3.0.1/unittest.html
It is not possible to pass fixture as argument so I'd have to use the plain asserts instead of unittest to solve this.

**Comment by jayvdb** [comment]
What is this?

Are you removing `unittest` support?
If so, this is a big no.
coala repos should work with `unittest`.  pytest features which are in addition can be used, but not the features which remove `unittest` support.

**Comment by nvzard** [comment]
It is not possible to provide additional configuration by setting variables at module level or as class attributes while using [FullStackTest](https://github.com/errbotio/errbot/blob/50d0c8918f3379e8bf60e28e3b7b32fa6fc30be9/errbot/backends/test.py#L465) to test the plugin.
I am not able to set `extra_plugin_dir = 'plugins'` due to this.

**Comment by gbin** [comment]
As per discussion in the Errbot channel:
```python
      class TestCommands(FullStackTest):
            def setUp(self, extra_plugin_dir=None, extra_test_file=None, loglevel=logging.DEBUG, extra_config=None):
                super().setUp(extra_plugin_dir='/something')
            def test_about(self):
                self.push_message('!about')
                self.assertIn('Err version', self.pop_message())
```

**Comment by nvzard** [comment]
@gbin had to explicitly call `self.start()` after `super().setUp(extra_plugin_dir='/something')` since `super()` returns a proxy object of class `FullStackTest`.
