### ISSUE TITLE
.gitignore: Add .pytest_cache

### ISSUE THREAD

**Issue by nvzard** [coala/corobo#536]
difficulty/newcomer

**Comment by utkarsh2102** [comment]
Hi,
Can I take up this task?

**Comment by nvzard** [comment]
@utkarsh2102 yeah sure!! 
Ask a maintainer to get assigned.

**Comment by utkarsh2102** [comment]
Thanks @nvzard.
@jayvdb, could you please assign the same to me?

**Comment by shikharvaish28** [comment]
Can I be assigned this issue, please?

**Comment by shikharvaish28** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [coala/corobo](https://trello.com/c/aW62hdWO/3-coala-corobo)
