### ISSUE TITLE
[GSoC '18] Add ability to ban from all gitter rooms at once 

### ISSUE THREAD

**Issue by nvzard** [coala/corobo#549]

**Comment by meetmangukiya** [comment]
Duplicate of https://github.com/coala/corobo/issues/462.
@nvzard it seems @Vamshi99 already has most of the work done, ban as well as unban.

**Comment by jayvdb** [comment]
Grrr... We should not have GSoC specific issues.

This is a duplicate of https://github.com/coala/corobo/issues/462
