### ISSUE TITLE
Use activate instead of __init__ for LabHub plugins

### ISSUE THREAD

**Issue by nvzard** [coala/corobo#554]

**Comment by jayvdb** [comment]
We have many issues which are effectively about this, allowing the plugin to start without automatically logging into with the tokens and fetching everything.

See https://github.com/coala/corobo/issues/357 and https://github.com/coala/corobo/issues/253 and others in labhub label.

All of those require removing the `__init__` and using the correct plugin startup sequence.  IMO this issue will be automatically fixed during one of those.
Just fixing `__init__` -> `activate` is ignoring the elephant in the room, and is code churn.
