### ISSUE TITLE
.coafile: Include PycodestyleBear and PyFlakesBear

### ISSUE THREAD

**Issue by nvzard** [coala/corobo#556]

**Comment by jayvdb** [comment]
How many errors are there at the moment.

Please give details when creating bugs.

**Comment by nvzard** [comment]
Since coala is not enabled to run on test files and PycodestyleBear is already enabled for rest of the files, so only PyFlakesBear needs to enabled

**Comment by jayvdb** [comment]
https://github.com/coala/corobo/issues/531 is better than PyflakesBear

**Comment by nvzard** [comment]
Ohk, I'll close this issue then.
