### ISSUE TITLE
Update .coafile to take tests/*.py into consideration.

### ISSUE THREAD

**Issue by nvzard** [coala/corobo#565]
difficulty/newcomer

**Comment by jayvdb** [comment]
How many errors are there at the moment.

Please give details when creating bugs.

**Comment by nvzard** [comment]
More than 35 errors are there at the moment including line length > 80, unused imports, E302 expected 2 blank lines, E127 continuation line over-indented for visual indent, E251 unexpected spaces around keyword/parameter equals, etc
