### ISSUE TITLE
Remove need for the empty data subdirectory

### ISSUE THREAD

**Issue by jayvdb** [coala/corobo#569]
`/data/` should be created at runtime if it is missing.

**Comment by jayvdb** [comment]
cross linking with https://gitlab.com/coala/mobans/issues/48

**Comment by jayvdb** [comment]
This *may* be an upstream fix.

**Comment by nvzard** [comment]
https://github.com/errbotio/errbot/pull/1232

**Comment by nvzard** [comment]
@jayvdb https://github.com/errbotio/errbot/pull/1232#issuecomment-400090465
