### ISSUE TITLE
final.py: Unused imports

### ISSUE THREAD

**Issue by MacBox7** [coala/corobo#585]
Pyflakes error report =>
```
./final.py:3: 'gensim.parsing.preprocessing.STOPWORDS' imported but unused
./final.py:4: 'gensim.utils.simple_preprocess' imported but unused
./final.py:6: 'nltk' imported but unused
```

**Comment by nvzard** [comment]
how come the `PyUnusedCodeBear` was not able to find these imports in the latest commit?
https://github.com/coala/corobo/commit/18a5b33aac03dfdedc977356c4335832e7ca501f

**Comment by MacBox7** [comment]
Even this =>
```
filters.py:1: 're' imported but unused
```

**Comment by MacBox7** [comment]
It seems to be an issue with `autoflake`. It is unable to detect these imports.

**Comment by Pawank221** [comment]
please assign me this issue.

**Comment by MacBox7** [comment]
Ask on `coala` group on gitter for assignment.

**Comment by ishanSrt** [comment]
apparently `PyUnusedCodeBear` fails a lot. I created a few issue about it last month or so
