### ISSUE TITLE
Remove dependency on nltk

### ISSUE THREAD

**Issue by jayvdb** [coala/corobo#593]
This was an unused dependency, and the import was removed in https://github.com/coala/corobo/pull/589

The entry in requirements.txt also needs to be removed.

**Comment by ssg2526** [comment]
hello, I am a newcomer and I want to take up this assignment. can you help me?

**Comment by jayvdb** [comment]
Hiya @ssg2526, I have sent you a email invite to join @coala .
After you accept it, read https://coala.io/newcomer and https://coala.io/commit carefully for tips on how to get your first PR right, and then submit a PR.
Much appreciated.
