### ISSUE TITLE
webservices.raml: Remove comment about merged todo

### ISSUE THREAD

**Issue by jayvdb** [coala/corobo#617]
`webservices.raml` includes a note about https://gitlab.com/coala/landing/merge_requests/39 , which is now merged.

The comment should be removed.

**Comment by mikebmc** [comment]
Hi there, I'm a newcomer. Would I be able to pick up this issue?

**Comment by jayvdb** [comment]
@mikebmc ive sent you a https://coala.io/newcomer invite

**Comment by mikebmc** [comment]
Thanks for the invite @jayvdb! 

I'm having some issues assigning this task through gitter. The newcomers doc suggests using the `corobo` command in gitter, however in gitter itself when I ask to join the main channel it suggests I try the `cobot` command in the cobot-test room. However, none of the commands seem to be working in the test room. Should I join the main room on gitter and use the `corobo assign` command there? I'm hesitant to spam that room with commands ;)

**Comment by jayvdb** [comment]
corobo has been offline for a bit , and enhanced quite a bit during the recent GSoC round, so should be ready to be brought online again soon.
