### ISSUE TITLE
On Zulip, ROOMS_TO_JOIN should contain valid Zulip rooms

### ISSUE THREAD

**Issue by jayvdb** [coala/corobo#635]
Following on from https://github.com/coala/corobo/pull/634 , the rooms list needs to be updated on backend Zulip to contain only rooms which exist on the coala Zulip server , otherwise there are lots of errors on startup.

Note that 'maintainers' (same as gitter coala/coala/maintainers) and 'gci-mentors-2018' (no gitter equivalent) are two private rooms the bot also needs to join on Zulip.

**Comment by jayvdb** [comment]
This is GCI task https://codein.withgoogle.com/dashboard/tasks/6377821476749312/

**Comment by why-does-ie-still-exist** [comment]
@jayvdb does the bot need to scrape zulip, use the zulip api, or is this just a static list of rooms pertinent to the bot?

**Comment by why-does-ie-still-exist** [comment]
> @jayvdb does the bot need to scrape zulip, use the zulip api, or is this just a static list of rooms pertinent to the bot?

Nevermind. I see what you mean(I think) I'll update the list. :-)

**Comment by jayvdb** [comment]
It can be a static list.
