### ISSUE TITLE
corobo CI failing due to Pycodestyle Warning W605

### ISSUE THREAD

**Issue by sladyn98** [coala/corobo#646]
In python 3.6, Unknown escapes consisting of \ and an ASCII letter in regular expressions will
cause an warning.In the upcoming python versions this would be treated as an error.
Owing to it pycodestyle have added this check for future Python versions.
Therefore Corobo's travis CI spits out the W606 warning for the following lines:
 `**** PycodestyleBear (W605) [Section: all.autopep8 | Severity: NORMAL] ****
!    ! W605 invalid escape sequence '\(' labhub_test.py`
`**** PycodestyleBear (W605) [Section: all.autopep8 | Severity: NORMAL] ****
!    ! W605 invalid escape sequence '\(' ban_test.py`
The link of the build can be found below:
https://travis-ci.org/coala/corobo/builds/488152691

**Comment by abhishalya** [comment]
corobo starts with small `c` also the issue if about fixing W605 (and not W606)?
