### ISSUE TITLE
Corobo CI Failing due to old pytest version

### ISSUE THREAD

**Issue by sladyn98** [coala/corobo#656]
The corobo build is failing due to a old version to pytest.
```Plugin 'xdist' could not be loaded: (pytest 3.6.4 (/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages), Requirement.parse('pytest>=4.4.0'))!```
Difficulty : newcomer

**Comment by abhishalya** [comment]
Should be closed? @sladyn98

**Comment by sladyn98** [comment]
@abhishalya does the build succeed?

**Comment by abhishalya** [comment]
Yep, https://travis-ci.org/coala/corobo/builds
