### ISSUE TITLE
Use a wrapper for gitlab + github support

### ISSUE THREAD

**Issue by meetmangukiya** [coala/corobo#76]

**Comment by meetmangukiya** [comment]
Seems like git-repo is far from stable for even issue assignments, but would be a good addition once completed.

**Comment by jayvdb** [comment]
The other wrapper is gitmate's [IGitt](https://gitlab.com/gitmate/open-source/IGitt)

**Comment by meetmangukiya** [comment]
IGitt looks like something that could work :+1:

**Comment by meetmangukiya** [comment]
See:
https://gitlab.com/gitmate/open-source/IGitt/issues/25
https://gitlab.com/gitmate/open-source/IGitt/issues/24
https://gitlab.com/gitmate/open-source/IGitt/issues/26

**Comment by meetmangukiya** [comment]
# We are using IGitt now
