### ISSUE TITLE
Add appveyor?

### ISSUE THREAD

**Issue by meetmangukiya** [coala/corobo#94]

**Comment by Makman2** [comment]
Do you wanna run it on Windows? Otherwise I would say just use Linux infrastructure^^ is usually better anyway^^

**Comment by meetmangukiya** [comment]
@Makman2 no, it'll be deployed on a linux powered server ;)

**Comment by Makman2** [comment]
I wouldn't use Windows testing then, maintaining windows compatibility is sadly some work... I would recommend to introduce AppVeyor only if you want to run it on Windows, and to port code to work there once needed.

**Comment by meetmangukiya** [comment]
hmm.. I guess then we shouldn't add AppVeyor and only add it only after a decade or so if windows takes server side better than linux ;P
