### ISSUE TITLE
Name for gitlab and github utilities plugin

### ISSUE THREAD

**Issue by meetmangukiya** [coala/corobo#99]
Please vote with a :+1: reaction on the candidates comment :3 

For the time-being it is named `LabHub` after considering 3 votes :P

**Comment by meetmangukiya** [comment]
LabHub

**Comment by meetmangukiya** [comment]
GitStar - suggested by @jayvdb

**Comment by yukiisbored** [comment]
GitMaid

**Comment by yukiisbored** [comment]
KannaGit

**Comment by yukiisbored** [comment]
Whoops, closed it by accident.

**Comment by meetmangukiya** [comment]
I don't think we are reaching a conclusion, and plugin names doesn't really matter. They just appear in the help list.
